-- Add comprehensive worker comp codes dataset
INSERT INTO public.worker_comp_codes (code, description, base_rate, category, hazard_level, state_code) VALUES
-- Professional Services
('8017', 'Consulting Engineer', 0.74, 'Professional', 'Low', 'ALL'),
('8018', 'Architect', 0.68, 'Professional', 'Low', 'ALL'),
('8031', 'Bank or Trust Company', 0.12, 'Financial', 'Low', 'ALL'),
('8032', 'Insurance Company', 0.25, 'Financial', 'Low', 'ALL'),
('8033', 'Real Estate', 0.52, 'Professional', 'Low', 'ALL'),
('8034', 'Accounting Firm', 0.31, 'Professional', 'Low', 'ALL'),
('8035', 'Law Firm', 0.48, 'Professional', 'Low', 'ALL'),
('8036', 'Physician', 0.45, 'Healthcare', 'Low', 'ALL'),
('8037', 'Dentist', 0.89, 'Healthcare', 'Low', 'ALL'),
('8038', 'Veterinarian', 1.24, 'Healthcare', 'Low', 'ALL'),
-- Retail and Services
('8039', 'Retail Store', 1.85, 'Retail', 'Low', 'ALL'),
('8040', 'Restaurant', 2.45, 'Hospitality', 'Medium', 'ALL'),
('8041', 'Hotel', 3.12, 'Hospitality', 'Medium', 'ALL'),
('8042', 'Clothing Store', 1.23, 'Retail', 'Low', 'ALL'),
('8043', 'Jewelry Store', 0.95, 'Retail', 'Low', 'ALL'),
('8044', 'Grocery Store', 2.78, 'Retail', 'Medium', 'ALL'),
('8045', 'Hardware Store', 3.45, 'Retail', 'Medium', 'ALL'),
-- Manufacturing
('2003', 'Bakery', 4.67, 'Manufacturing', 'Medium', 'ALL'),
('2016', 'Brewery', 5.89, 'Manufacturing', 'Medium', 'ALL'),
('2501', 'Furniture Manufacturing', 7.23, 'Manufacturing', 'High', 'ALL'),
('2585', 'Woodworking', 8.94, 'Manufacturing', 'High', 'ALL'),
('2702', 'Printing', 3.45, 'Manufacturing', 'Medium', 'ALL'),
('2710', 'Paper Manufacturing', 6.78, 'Manufacturing', 'High', 'ALL'),
('2883', 'Chemical Manufacturing', 4.23, 'Manufacturing', 'Medium', 'ALL'),
('2960', 'Plastics Manufacturing', 5.67, 'Manufacturing', 'Medium', 'ALL'),
-- Construction
('5022', 'Masonry', 11.45, 'Construction', 'High', 'ALL'),
('5037', 'Concrete Work', 10.23, 'Construction', 'High', 'ALL'),
('5040', 'Carpentry', 13.67, 'Construction', 'High', 'ALL'),
('5057', 'Plumbing', 9.78, 'Construction', 'High', 'ALL'),
('5075', 'Electrical Work', 8.45, 'Construction', 'High', 'ALL'),
('5102', 'Carpentry - Residential', 12.81, 'Construction', 'High', 'ALL'),
('5146', 'Roofing', 16.85, 'Construction', 'High', 'ALL'),
('5183', 'Painting', 7.94, 'Construction', 'Medium', 'ALL'),
('5190', 'Carpentry - Commercial', 15.23, 'Construction', 'High', 'ALL'),
('5213', 'Concrete Construction', 8.92, 'Construction', 'High', 'ALL'),
('5221', 'Concrete Construction - Residential', 9.45, 'Construction', 'High', 'ALL'),
('5348', 'Excavation', 6.78, 'Construction', 'Medium', 'ALL'),
('5403', 'Carpentry - Detached One or Two Family Dwellings', 14.56, 'Construction', 'High', 'ALL'),
('5437', 'Carpentry - Multi-Story Construction', 17.89, 'Construction', 'High', 'ALL'),
('5474', 'Painting - Interior', 6.78, 'Construction', 'Medium', 'ALL'),
('5506', 'Street or Road Construction', 7.23, 'Construction', 'Medium', 'ALL'),
('5551', 'Water Well Drilling', 12.34, 'Construction', 'High', 'ALL'),
('5645', 'Carpentry - Installation of Cabinets or Interior Fixtures', 11.23, 'Construction', 'High', 'ALL'),
-- Transportation
('7219', 'Truckmen - Local', 4.35, 'Transportation', 'Medium', 'ALL'),
('7228', 'Trucking - Long Distance', 5.67, 'Transportation', 'Medium', 'ALL'),
('7380', 'Drivers - Truck', 7.26, 'Transportation', 'Medium', 'ALL'),
('7382', 'Drivers - Taxi', 8.45, 'Transportation', 'Medium', 'ALL'),
('7390', 'Drivers - Chauffeur', 3.45, 'Transportation', 'Medium', 'ALL'),
('7394', 'Drivers - Bus', 6.78, 'Transportation', 'Medium', 'ALL'),
('7395', 'Drivers - School Bus', 4.23, 'Transportation', 'Medium', 'ALL'),
('7396', 'Drivers - Ambulance', 9.45, 'Transportation', 'Medium', 'ALL'),
('7421', 'Delivery', 5.89, 'Transportation', 'Medium', 'ALL'),
('7520', 'Air Transportation', 2.34, 'Transportation', 'Medium', 'ALL'),
-- Services
('8006', 'Janitor', 2.89, 'Services', 'Medium', 'ALL'),
('8013', 'Landscape Gardening', 5.67, 'Services', 'Medium', 'ALL'),
('8021', 'Cleaning Service', 3.45, 'Services', 'Medium', 'ALL'),
('8111', 'Office Machine Repair', 2.78, 'Services', 'Medium', 'ALL'),
('8380', 'Automobile Service or Repair', 6.78, 'Services', 'Medium', 'ALL'),
('8381', 'Automobile Garage', 4.56, 'Services', 'Medium', 'ALL'),
('8385', 'Automobile Dealers', 2.34, 'Services', 'Low', 'ALL'),
('8601', 'Architect or Engineer', 0.74, 'Professional', 'Low', 'ALL'),
('8602', 'Surveyor', 1.23, 'Professional', 'Low', 'ALL'),
('8603', 'Draftsman', 0.89, 'Professional', 'Low', 'ALL'),
('8742', 'Salesperson - Outside', 1.45, 'Sales', 'Low', 'ALL'),
('8743', 'Salesperson - Inside', 0.67, 'Sales', 'Low', 'ALL'),
('8810', 'Clerical Office Employees', 0.35, 'Office', 'Low', 'ALL'),
('8820', 'Attorney - All Employees', 0.54, 'Professional', 'Low', 'ALL'),
('8832', 'Accountant - All Employees', 0.27, 'Professional', 'Low', 'ALL'),
('8833', 'Insurance Agency - All Employees', 0.89, 'Professional', 'Low', 'ALL'),
('8834', 'Real Estate Agency - All Employees', 0.52, 'Professional', 'Low', 'ALL'),
('8835', 'Collection Agency', 0.78, 'Professional', 'Low', 'ALL'),
('8868', 'College or University', 0.45, 'Education', 'Low', 'ALL'),
('8869', 'School - Elementary or Secondary', 0.89, 'Education', 'Low', 'ALL'),
('8871', 'Daycare', 1.23, 'Education', 'Low', 'ALL'),
-- Building Operations
('9012', 'Building Operation - Apartment House', 2.78, 'Building Operations', 'Medium', 'ALL'),
('9015', 'Building Operation - Office Building', 2.38, 'Building Operations', 'Medium', 'ALL'),
('9016', 'Building Operation - Hotel', 3.45, 'Building Operations', 'Medium', 'ALL'),
('9052', 'Hospital - All Employees', 1.89, 'Healthcare', 'Medium', 'ALL'),
('9058', 'Nursing Home', 4.67, 'Healthcare', 'Medium', 'ALL'),
('9101', 'Building Operation - Mercantile Building', 3.15, 'Building Operations', 'Medium', 'ALL'),
('9102', 'Building Operation - Department Store', 2.89, 'Building Operations', 'Medium', 'ALL'),
-- Agriculture
('0005', 'Farming', 7.89, 'Agriculture', 'Medium', 'ALL'),
('0008', 'Cattle Ranching', 6.45, 'Agriculture', 'Medium', 'ALL'),
('0016', 'Dairy', 5.67, 'Agriculture', 'Medium', 'ALL'),
('0035', 'Poultry', 4.23, 'Agriculture', 'Medium', 'ALL'),
('0042', 'Vegetable Farming', 8.45, 'Agriculture', 'Medium', 'ALL'),
('0050', 'Fruit Farming', 7.23, 'Agriculture', 'Medium', 'ALL'),
('0083', 'Tree Service', 12.34, 'Agriculture', 'High', 'ALL'),
-- Healthcare
('8835', 'Medical Office', 1.45, 'Healthcare', 'Low', 'ALL'),
('8859', 'Convalescent Home', 5.67, 'Healthcare', 'Medium', 'ALL'),
('9014', 'Hospital - Professional Employees', 0.89, 'Healthcare', 'Low', 'ALL'),
('9040', 'Hospital - All Other Employees', 2.34, 'Healthcare', 'Medium', 'ALL'),
('9048', 'Physical Therapy', 1.78, 'Healthcare', 'Low', 'ALL'),
('9049', 'Ambulance Service', 8.45, 'Healthcare', 'Medium', 'ALL'),
('9050', 'Nursing Service', 3.45, 'Healthcare', 'Medium', 'ALL'),
('9051', 'Home Health Care', 4.67, 'Healthcare', 'Medium', 'ALL'),
-- Technology
('8601', 'Computer Programming', 0.35, 'Technology', 'Low', 'ALL'),
('8602', 'Software Development', 0.28, 'Technology', 'Low', 'ALL'),
('8603', 'Data Processing', 0.42, 'Technology', 'Low', 'ALL'),
('8604', 'Computer Repair', 1.23, 'Technology', 'Low', 'ALL'),
('8605', 'Telecommunications', 2.34, 'Technology', 'Medium', 'ALL')
ON CONFLICT (code) DO UPDATE SET 
  description = EXCLUDED.description,
  base_rate = EXCLUDED.base_rate,
  category = EXCLUDED.category,
  hazard_level = EXCLUDED.hazard_level,
  state_code = EXCLUDED.state_code,
  updated_at = now();